### PR TITLE
Use namespace to expose inner interfaces in a structured manner

### LINKED ISSUE #162: Difficulties consuming the new types
I am having difficulties consuming the new types. One specific example is I save a `Watch` instance created via `consul.watch()`, but cannot properly specify the type in the class definition.

As someone who only has some Typescript experience, I *think* the problem may be that the new declaration files do not specify namespaces? This causes any top-down usage to be typed, but no types to be exported other than `lib/index.d.ts`'s export of `Consul`.

So when typing things:

```
import Consul from 'consul';

class Foo {
  consul: Consul; // can type this because Consul is exported inline with the class itself
  watch?: Watch; // this fails to compile, because the Watch type is not exported.
}

// ...nside a Foo instance
// tsc knows that this.watch should be of type "Watch" since internally it has access to the type.
// However, there is no way to reference it in the above class definition.
this.watch = this.consul.watch({method, options});
```

### PR DESCRIPTION
**Pull request by UNIDY2002**
Fix #162

### CODE REVIEW

**Comment by silas** [comment]
@UNIDY2002 Nice!

I added [tsd](https://github.com/tsdjs/tsd) in #164, do you mind merging `main` into this branch and adding a couple of `exceptType`s to `test-d/index.test-d.ts` for how one might use these types.

**Comment by UNIDY2002** [comment]
@silas I'd like to. I'll add some cases after the weekend.

**Comment by brandonw** [comment]
Wow! Thanks for the fast turnaround on this @UNIDY2002 ❤️

**Comment by UNIDY2002** [comment]
@silas This PR is ready for review

**Pull request closed without merging**
